openapi: 3.0.1
info:
  title: Fruit API
  version: 1.0.0

paths:
  /fruits:
    get:
      summary: "Alle Fr端chte abrufen"
      operationId: getAllFruits
      responses:
        "200":
          description: "Liste aller Fr端chte"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Fruit"
    post:
      summary: "Neue Frucht hinzuf端gen"
      operationId: addFruit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fruit"
      responses:
        "201":
          description: "Frucht erfolgreich hinzugef端gt"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fruit"

components:
  schemas:
    Fruit:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string