name: Docs

on:
  push:
    branches:
      - 'main'
    paths:
      - asciidocs/**

permissions:
  contents: write

jobs:
  build:
    name: Build & Publish 🚀
    runs-on: ubuntu-latest
    env:
      INPUTPATH: asciidocs/docs
      OUTPUTPATH: asciidocs/html
      BRANCH: gh-pages

    steps:
      # Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Erstelle Ausgabeverzeichnis und Konvertiere .adoc zu HTML
      - name: Convert AsciiDoc to HTML
        run: |
          mkdir -p ${{ env.OUTPUTPATH }}
          docker run --rm \
            -v $PWD/${{ env.INPUTPATH }}:/documents \
            asciidoctor/docker-asciidoctor \
            asciidoctor -b html5 -r asciidoctor-diagram -a showtitle -a toc=left -D /documents/html /documents/*.adoc

      # Deployment auf GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: ${{ env.BRANCH }}
          folder: ${{ env.OUTPUTPATH }}
